// src/lib/products.ts

export type Product = {
  id: string;
  title: string;
  store: string;
  imageUrl?: string;
  priceUSD: number;
  estimatedUSD: number;
  category: string;
  slug: string; // para URLs tipo /producto/sony-playstation-5
  description?: string;
};

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Nike Air Max 270 White/Black",
    store: "Nike",
    priceUSD: 150,
    estimatedUSD: 210,
    category: "Zapatillas",
    slug: "nike-air-max-270-white-black",
    description: "Zapatillas Nike Air Max 270 originales importadas desde USA.",
  },
  {
    id: "2",
    title: "Apple AirPods Pro (2da generación)",
    store: "Amazon",
    priceUSD: 249,
    estimatedUSD: 320,
    category: "Electrónica",
    slug: "apple-airpods-pro-2",
    description: "Auriculares Apple AirPods Pro 2 con estuche de carga MagSafe.",
  },
  {
    id: "3",
    title: "Sony PlayStation 5 Console",
    store: "BestBuy",
    priceUSD: 499,
    estimatedUSD: 680,
    category: "Gaming",
    slug: "sony-playstation-5-console",
    description: "Consola Sony PlayStation 5 versión estándar con lector de discos.",
  },
  {
    id: "4",
    title: "Samsung Galaxy S24 128GB",
    store: "eBay",
    priceUSD: 799,
    estimatedUSD: 1040,
    category: "Celulares",
    slug: "samsung-galaxy-s24-128gb",
    description: "Celular Samsung Galaxy S24 128GB desbloqueado para todas las bandas.",
  },

  // ========= ZAPATILLAS =========
  {
    id: "5",
    title: "Nike Air Force 1 '07 White",
    store: "Nike",
    priceUSD: 115,
    estimatedUSD: 180,
    category: "Zapatillas",
    slug: "nike-air-force-1-07-white",
    description: "Clásicas Nike Air Force 1 '07 color blanco, ícono urbano.",
  },
  {
    id: "6",
    title: "Nike Dunk Low Retro Black/White",
    store: "Nike",
    priceUSD: 120,
    estimatedUSD: 185,
    category: "Zapatillas",
    slug: "nike-dunk-low-retro-black-white",
    description: "Zapatillas Nike Dunk Low color Panda, uno de los modelos más buscados.",
  },
  {
    id: "7",
    title: "Adidas Ultraboost 22 Core Black",
    store: "Adidas",
    priceUSD: 190,
    estimatedUSD: 260,
    category: "Zapatillas",
    slug: "adidas-ultraboost-22-core-black",
    description: "Adidas Ultraboost 22 con amortiguación Boost para running y uso diario.",
  },
  {
    id: "8",
    title: "New Balance 574 Core Grey",
    store: "New Balance",
    priceUSD: 90,
    estimatedUSD: 150,
    category: "Zapatillas",
    slug: "new-balance-574-core-grey",
    description: "New Balance 574 en tono gris clásico, cómodas y versátiles.",
  },
  {
    id: "9",
    title: "Nike Air Jordan 1 Mid Chicago",
    store: "Nike",
    priceUSD: 150,
    estimatedUSD: 230,
    category: "Zapatillas",
    slug: "nike-air-jordan-1-mid-chicago",
    description: "Air Jordan 1 Mid con el mítico colorway Chicago rojo/blanco/negro.",
  },
  {
    id: "10",
    title: "Adidas Forum Low White/Blue",
    store: "Adidas",
    priceUSD: 110,
    estimatedUSD: 175,
    category: "Zapatillas",
    slug: "adidas-forum-low-white-blue",
    description: "Adidas Forum Low estilo retro, perfectas para uso urbano.",
  },
  {
    id: "11",
    title: "Converse Chuck Taylor All Star High Top Black",
    store: "Amazon",
    priceUSD: 65,
    estimatedUSD: 120,
    category: "Zapatillas",
    slug: "converse-chuck-taylor-all-star-high-black",
    description: "Converse Chuck Taylor clásicas en caña alta color negro.",
  },
  {
    id: "12",
    title: "Vans Old Skool Black/White",
    store: "Vans",
    priceUSD: 70,
    estimatedUSD: 125,
    category: "Zapatillas",
    slug: "vans-old-skool-black-white",
    description: "Vans Old Skool negras con franja blanca, modelo icónico del skate.",
  },
  {
    id: "13",
    title: "Nike ZoomX Vaporfly Next% 3",
    store: "Nike",
    priceUSD: 260,
    estimatedUSD: 340,
    category: "Zapatillas",
    slug: "nike-zoomx-vaporfly-next-3",
    description: "Zapatillas de alto rendimiento para maratón con placa de carbono.",
  },
  {
    id: "14",
    title: "Hoka One One Clifton 9",
    store: "Amazon",
    priceUSD: 144,
    estimatedUSD: 210,
    category: "Zapatillas",
    slug: "hoka-one-one-clifton-9",
    description: "Hoka Clifton 9 con máxima amortiguación para corredores de fondo.",
  },

  // ========= ELECTRÓNICA =========
  {
    id: "15",
    title: "Apple iPad 10.9'' (10th Gen) 64GB Wi-Fi",
    store: "Apple",
    priceUSD: 449,
    estimatedUSD: 600,
    category: "Electrónica",
    slug: "apple-ipad-10th-gen-64gb-wifi",
    description: "iPad de 10ª generación 10.9\" con chip A14 y 64GB de almacenamiento.",
  },
  {
    id: "16",
    title: "Amazon Kindle Paperwhite 8 GB (11th Gen)",
    store: "Amazon",
    priceUSD: 149,
    estimatedUSD: 210,
    category: "Electrónica",
    slug: "amazon-kindle-paperwhite-11th-gen-8gb",
    description: "Kindle Paperwhite resistente al agua con pantalla de 6.8\".",
  },
  {
    id: "17",
    title: "Bose QuietComfort 45 Wireless Headphones",
    store: "Amazon",
    priceUSD: 279,
    estimatedUSD: 360,
    category: "Electrónica",
    slug: "bose-quietcomfort-45-wireless-headphones",
    description: "Auriculares Bose con cancelación activa de ruido y modo Aware.",
  },
  {
    id: "18",
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    store: "BestBuy",
    priceUSD: 399,
    estimatedUSD: 520,
    category: "Electrónica",
    slug: "sony-wh-1000xm5-wireless-headphones",
    description: "Auriculares Sony WH-1000XM5, referencia en cancelación de ruido.",
  },
  {
    id: "19",
    title: "Apple Watch Series 9 GPS 41mm",
    store: "Apple",
    priceUSD: 399,
    estimatedUSD: 530,
    category: "Electrónica",
    slug: "apple-watch-series-9-gps-41mm",
    description: "Apple Watch Series 9 con pantalla always-on y sensores avanzados.",
  },
  {
    id: "20",
    title: "Logitech MX Master 3S Wireless Mouse",
    store: "Amazon",
    priceUSD: 99,
    estimatedUSD: 160,
    category: "Electrónica",
    slug: "logitech-mx-master-3s-wireless-mouse",
    description: "Mouse premium Logitech MX Master 3S para productividad avanzada.",
  },
  {
    id: "21",
    title: "Anker PowerCore 20000mAh Power Bank",
    store: "Amazon",
    priceUSD: 59,
    estimatedUSD: 110,
    category: "Electrónica",
    slug: "anker-powercore-20000mah-power-bank",
    description: "Batería externa Anker de 20.000mAh, ideal para viajes.",
  },
  {
    id: "22",
    title: "GoPro HERO12 Black Action Camera",
    store: "BestBuy",
    priceUSD: 399,
    estimatedUSD: 540,
    category: "Electrónica",
    slug: "gopro-hero12-black-action-camera",
    description: "Cámara de acción GoPro HERO12 Black para video 5.3K.",
  },
  {
    id: "23",
    title: "Apple Magic Keyboard with Touch ID",
    store: "Apple",
    priceUSD: 149,
    estimatedUSD: 210,
    category: "Electrónica",
    slug: "apple-magic-keyboard-touch-id",
    description: "Teclado Magic Keyboard con Touch ID para Mac con Apple Silicon.",
  },
  {
    id: "24",
    title: "Samsung 27'' Odyssey G5 Gaming Monitor 144Hz",
    store: "Amazon",
    priceUSD: 299,
    estimatedUSD: 420,
    category: "Electrónica",
    slug: "samsung-odyssey-g5-27-144hz",
    description: "Monitor gamer curvo 27\" QHD 144Hz ideal para PC y consolas.",
  },

  // ========= CELULARES =========
  {
    id: "25",
    title: "Apple iPhone 15 128GB",
    store: "Apple",
    priceUSD: 799,
    estimatedUSD: 1080,
    category: "Celulares",
    slug: "apple-iphone-15-128gb",
    description: "iPhone 15 de 128GB, pantalla de 6.1\" y conector USB-C.",
  },
  {
    id: "26",
    title: "Apple iPhone 15 Pro 256GB",
    store: "Apple",
    priceUSD: 1199,
    estimatedUSD: 1580,
    category: "Celulares",
    slug: "apple-iphone-15-pro-256gb",
    description: "iPhone 15 Pro de 256GB, chasis de titanio y cámara avanzada.",
  },
  {
    id: "27",
    title: "Google Pixel 8 128GB",
    store: "BestBuy",
    priceUSD: 699,
    estimatedUSD: 960,
    category: "Celulares",
    slug: "google-pixel-8-128gb",
    description: "Google Pixel 8 con Android puro y cámara computacional.",
  },
  {
    id: "28",
    title: "OnePlus 12 256GB",
    store: "Amazon",
    priceUSD: 799,
    estimatedUSD: 1080,
    category: "Celulares",
    slug: "oneplus-12-256gb",
    description: "OnePlus 12 con pantalla AMOLED 120Hz y carga ultra rápida.",
  },
  {
    id: "29",
    title: "Samsung Galaxy A55 5G 128GB",
    store: "Amazon",
    priceUSD: 449,
    estimatedUSD: 620,
    category: "Celulares",
    slug: "samsung-galaxy-a55-5g-128gb",
    description: "Gama media premium de Samsung con excelente relación precio/calidad.",
  },
  {
    id: "30",
    title: "Motorola Edge 50 Fusion 256GB",
    store: "Amazon",
    priceUSD: 399,
    estimatedUSD: 560,
    category: "Celulares",
    slug: "motorola-edge-50-fusion-256gb",
    description: "Motorola Edge con gran batería y pantalla pOLED.",
  },

  // ========= GAMING =========
  {
    id: "31",
    title: "Xbox Series X 1TB Console",
    store: "BestBuy",
    priceUSD: 499,
    estimatedUSD: 680,
    category: "Gaming",
    slug: "xbox-series-x-1tb-console",
    description: "Consola Xbox Series X con 1TB de almacenamiento.",
  },
  {
    id: "32",
    title: "Nintendo Switch OLED Model",
    store: "Amazon",
    priceUSD: 349,
    estimatedUSD: 480,
    category: "Gaming",
    slug: "nintendo-switch-oled-model",
    description: "Nintendo Switch OLED con pantalla mejorada y dock con LAN.",
  },
  {
    id: "33",
    title: "Sony DualSense Wireless Controller White",
    store: "Amazon",
    priceUSD: 69,
    estimatedUSD: 120,
    category: "Gaming",
    slug: "sony-dualsense-wireless-controller-white",
    description: "Control inalámbrico DualSense para PlayStation 5.",
  },
  {
    id: "34",
    title: "Logitech G Pro X Mechanical Gaming Keyboard",
    store: "Amazon",
    priceUSD: 129,
    estimatedUSD: 190,
    category: "Gaming",
    slug: "logitech-g-pro-x-mechanical-gaming-keyboard",
    description: "Teclado mecánico gamer con switches intercambiables.",
  },
  {
    id: "35",
    title: "Razer Viper V2 Pro Wireless Gaming Mouse",
    store: "Amazon",
    priceUSD: 149,
    estimatedUSD: 210,
    category: "Gaming",
    slug: "razer-viper-v2-pro-wireless-gaming-mouse",
    description: "Mouse gamer ultraligero con sensor de alta precisión.",
  },
  {
    id: "36",
    title: "SteelSeries Arctis Nova 7 Wireless Headset",
    store: "Amazon",
    priceUSD: 179,
    estimatedUSD: 250,
    category: "Gaming",
    slug: "steelseries-arctis-nova-7-wireless-headset",
    description: "Auriculares gamer inalámbricos compatibles con PC y consolas.",
  },

  // ========= HOGAR =========
  {
    id: "37",
    title: "Instant Pot Duo 7-in-1 Pressure Cooker 6 Qt",
    store: "Amazon",
    priceUSD: 99,
    estimatedUSD: 160,
    category: "Hogar",
    slug: "instant-pot-duo-7-in-1-6qt",
    description: "Olla a presión eléctrica multifunción, ideal para meal prep.",
  },
  {
    id: "38",
    title: "Dyson V11 Cordless Vacuum Cleaner",
    store: "Dyson",
    priceUSD: 599,
    estimatedUSD: 820,
    category: "Hogar",
    slug: "dyson-v11-cordless-vacuum-cleaner",
    description: "Aspiradora inalámbrica Dyson V11 con alta potencia de succión.",
  },
  {
    id: "39",
    title: "Nespresso Vertuo Plus Coffee and Espresso Maker",
    store: "Amazon",
    priceUSD: 189,
    estimatedUSD: 260,
    category: "Hogar",
    slug: "nespresso-vertuo-plus-coffee-espresso",
    description: "Cafetera Nespresso Vertuo para cápsulas de café y espresso.",
  },
  {
    id: "40",
    title: "Philips Hue White and Color Ambiance Starter Kit",
    store: "Amazon",
    priceUSD: 199,
    estimatedUSD: 280,
    category: "Hogar",
    slug: "philips-hue-white-color-ambiance-starter-kit",
    description: "Kit de iluminación inteligente con 3 lámparas y puente Hue.",
  },
  {
    id: "41",
    title: "KitchenAid Artisan 5-Quart Stand Mixer",
    store: "Amazon",
    priceUSD: 449,
    estimatedUSD: 620,
    category: "Hogar",
    slug: "kitchenaid-artisan-5qt-stand-mixer",
    description: "Batidora de pie KitchenAid para repostería y panificados.",
  },
  {
    id: "42",
    title: "Brita Water Filter Pitcher 10 Cups",
    store: "Amazon",
    priceUSD: 39,
    estimatedUSD: 95,
    category: "Hogar",
    slug: "brita-water-filter-pitcher-10-cups",
    description: "Jarra Brita con filtro para mejorar el sabor del agua.",
  },

  // ========= BELLEZA =========
  {
    id: "43",
    title: "CeraVe Hydrating Facial Cleanser 16 oz",
    store: "Amazon",
    priceUSD: 16,
    estimatedUSD: 55,
    category: "Belleza",
    slug: "cerave-hydrating-facial-cleanser-16oz",
    description: "Limpiador facial hidratante para piel normal a seca.",
  },
  {
    id: "44",
    title: "The Ordinary Niacinamide 10% + Zinc 1% Serum",
    store: "Sephora",
    priceUSD: 12,
    estimatedUSD: 45,
    category: "Belleza",
    slug: "the-ordinary-niacinamide-10-zinc-1",
    description: "Sérum para reducir manchas, controlar oleosidad y mejorar textura.",
  },
  {
    id: "45",
    title: "La Roche-Posay Anthelios Melt-in Milk SPF 60",
    store: "Amazon",
    priceUSD: 38,
    estimatedUSD: 90,
    category: "Belleza",
    slug: "la-roche-posay-anthelios-spf-60",
    description: "Protector solar corporal y facial de amplio espectro.",
  },
  {
    id: "46",
    title: "Olaplex No. 3 Hair Perfector 100ml",
    store: "Sephora",
    priceUSD: 30,
    estimatedUSD: 80,
    category: "Belleza",
    slug: "olaplex-no3-hair-perfector-100ml",
    description: "Tratamiento reparador para cabello dañado por tintes o calor.",
  },
  {
    id: "47",
    title: "Revlon One-Step Volumizer Plus Hair Dryer Brush",
    store: "Amazon",
    priceUSD: 69,
    estimatedUSD: 130,
    category: "Belleza",
    slug: "revlon-one-step-volumizer-plus",
    description: "Cepillo secador que alisa y da volumen en un solo paso.",
  },
  {
    id: "48",
    title: "Laneige Lip Sleeping Mask Berry",
    store: "Sephora",
    priceUSD: 24,
    estimatedUSD: 70,
    category: "Belleza",
    slug: "laneige-lip-sleeping-mask-berry",
    description: "Mascarilla nocturna para labios ultra hidratante.",
  },

  // ========= ROPA Y MODA =========
  {
    id: "49",
    title: "Levi's 511 Slim Fit Men's Jeans Dark Blue",
    store: "Levi's",
    priceUSD: 79,
    estimatedUSD: 140,
    category: "Ropa y moda",
    slug: "levis-511-slim-fit-mens-jeans-dark-blue",
    description: "Jeans Levi's 511 de corte slim en denim azul oscuro.",
  },
  {
    id: "50",
    title: "Levi's 501 Original Fit Men's Jeans Medium Wash",
    store: "Levi's",
    priceUSD: 89,
    estimatedUSD: 150,
    category: "Ropa y moda",
    slug: "levis-501-original-fit-mens-jeans-medium-wash",
    description: "Clásico jean Levi's 501 corte recto.",
  },
  {
    id: "51",
    title: "Nike Sportswear Club Fleece Hoodie Black",
    store: "Nike",
    priceUSD: 65,
    estimatedUSD: 120,
    category: "Ropa y moda",
    slug: "nike-sportswear-club-fleece-hoodie-black",
    description: "Buzo con capucha Nike Club Fleece color negro.",
  },
  {
    id: "52",
    title: "The North Face 1996 Retro Nuptse Jacket Black",
    store: "The North Face",
    priceUSD: 320,
    estimatedUSD: 430,
    category: "Ropa y moda",
    slug: "the-north-face-1996-retro-nuptse-jacket-black",
    description: "Campera inflable The North Face Nuptse clásica, muy abrigada.",
  },
  {
    id: "53",
    title: "Patagonia Better Sweater Fleece Jacket",
    store: "Patagonia",
    priceUSD: 139,
    estimatedUSD: 210,
    category: "Ropa y moda",
    slug: "patagonia-better-sweater-fleece-jacket",
    description: "Campera de polar Patagonia, ideal para climas frescos.",
  },
  {
    id: "54",
    title: "Calvin Klein 3-Pack Men's Boxer Briefs Black",
    store: "Amazon",
    priceUSD: 45,
    estimatedUSD: 95,
    category: "Ropa y moda",
    slug: "calvin-klein-3-pack-mens-boxer-briefs-black",
    description: "Pack de 3 bóxers Calvin Klein en color negro.",
  },

  // ========= NIÑOS =========
  {
    id: "55",
    title: "LEGO Star Wars The Mandalorian N-1 Starfighter Set",
    store: "Amazon",
    priceUSD: 69,
    estimatedUSD: 130,
    category: "Niños",
    slug: "lego-star-wars-the-mandalorian-n1-starfighter-set",
    description: "Set LEGO de la nave N-1 de The Mandalorian.",
  },
  {
    id: "56",
    title: "LEGO Classic Large Creative Brick Box",
    store: "Amazon",
    priceUSD: 59,
    estimatedUSD: 115,
    category: "Niños",
    slug: "lego-classic-large-creative-brick-box",
    description: "Caja grande de ladrillos LEGO para construir libremente.",
  },
  {
    id: "57",
    title: "Crayola Inspiration Art Case Coloring Set",
    store: "Amazon",
    priceUSD: 29,
    estimatedUSD: 80,
    category: "Niños",
    slug: "crayola-inspiration-art-case-coloring-set",
    description: "Set de arte Crayola con marcadores, lápices y crayones.",
  },
  {
    id: "58",
    title: "Nintendo Switch Mario Kart 8 Deluxe",
    store: "Amazon",
    priceUSD: 59,
    estimatedUSD: 110,
    category: "Niños",
    slug: "nintendo-switch-mario-kart-8-deluxe",
    description: "Videojuego Mario Kart 8 Deluxe para Nintendo Switch.",
  },
  {
    id: "59",
    title: "Disney Princess Royal Shimmer Doll Collection",
    store: "Amazon",
    priceUSD: 99,
    estimatedUSD: 170,
    category: "Niños",
    slug: "disney-princess-royal-shimmer-doll-collection",
    description: "Colección de muñecas Disney Princess con vestidos brillantes.",
  },
  {
    id: "60",
    title: "PUMA Kids' Anzarun Lite Sneakers",
    store: "Amazon",
    priceUSD: 49,
    estimatedUSD: 100,
    category: "Niños",
    slug: "puma-kids-anzarun-lite-sneakers",
    description: "Zapatillas PUMA para niños, livianas y cómodas.",
  },

  // ========= RELOJES =========
  {
    id: "61",
    title: "Casio G-Shock GA2100-1A1",
    store: "Amazon",
    priceUSD: 99,
    estimatedUSD: 170,
    category: "Relojes",
    slug: "casio-g-shock-ga2100-1a1",
    description: "Reloj Casio G-Shock GA2100 en negro mate, ultrarresistente.",
  },
  {
    id: "62",
    title: "Seiko 5 Sports Automatic SRPD55",
    store: "Amazon",
    priceUSD: 295,
    estimatedUSD: 410,
    category: "Relojes",
    slug: "seiko-5-sports-automatic-srpd55",
    description: "Reloj automático Seiko 5 Sports con correa de acero.",
  },
  {
    id: "63",
    title: "Timex Weekender 40mm Fabric Strap Watch",
    store: "Amazon",
    priceUSD: 49,
    estimatedUSD: 105,
    category: "Relojes",
    slug: "timex-weekender-40mm-fabric-strap-watch",
    description: "Reloj casual Timex Weekender con correa textil intercambiable.",
  },
  {
    id: "64",
    title: "Apple Watch SE (2nd Gen) GPS 44mm",
    store: "Apple",
    priceUSD: 279,
    estimatedUSD: 380,
    category: "Relojes",
    slug: "apple-watch-se-2nd-gen-gps-44mm",
    description: "Apple Watch SE 2da generación con GPS y funciones esenciales.",
  },
  {
    id: "65",
    title: "Garmin Forerunner 265 GPS Running Watch",
    store: "Garmin",
    priceUSD: 449,
    estimatedUSD: 590,
    category: "Relojes",
    slug: "garmin-forerunner-265-gps-running-watch",
    description: "Reloj Garmin para running y triatlón con métricas avanzadas.",
  },
  {
    id: "66",
    title: "Fossil Men's Machine Stainless Steel Watch",
    store: "Amazon",
    priceUSD: 139,
    estimatedUSD: 210,
    category: "Relojes",
    slug: "fossil-mens-machine-stainless-steel-watch",
    description: "Reloj Fossil de acero con diseño industrial.",
  },

  // ========= ACCESORIOS =========
  {
    id: "67",
    title: "Herschel Little America Backpack Black",
    store: "Amazon",
    priceUSD: 109,
    estimatedUSD: 180,
    category: "Accesorios",
    slug: "herschel-little-america-backpack-black",
    description: "Mochila Herschel con estilo montañés y gran capacidad.",
  },
  {
    id: "68",
    title: "The North Face Base Camp Duffel Medium",
    store: "The North Face",
    priceUSD: 149,
    estimatedUSD: 230,
    category: "Accesorios",
    slug: "the-north-face-base-camp-duffel-medium",
    description: "Bolso tipo duffel ultra resistente para viajes.",
  },
  {
    id: "69",
    title: "Ray-Ban Wayfarer Classic Sunglasses Black",
    store: "Ray-Ban",
    priceUSD: 168,
    estimatedUSD: 240,
    category: "Accesorios",
    slug: "ray-ban-wayfarer-classic-sunglasses-black",
    description: "Lentes Ray-Ban Wayfarer originales en negro.",
  },
  {
    id: "70",
    title: "Oakley Holbrook Prizm Polarized Sunglasses",
    store: "Oakley",
    priceUSD: 213,
    estimatedUSD: 290,
    category: "Accesorios",
    slug: "oakley-holbrook-prizm-polarized-sunglasses",
    description: "Lentes Oakley Holbrook con lentes Prizm polarizadas.",
  },
  {
    id: "71",
    title: "Apple AirTag 4 Pack",
    store: "Apple",
    priceUSD: 99,
    estimatedUSD: 160,
    category: "Accesorios",
    slug: "apple-airtag-4-pack",
    description: "Pack de 4 AirTag para rastrear llaves, bolsos y más.",
  },
  {
    id: "72",
    title: "Anker USB-C Hub 7-in-1 for MacBook",
    store: "Amazon",
    priceUSD: 69,
    estimatedUSD: 130,
    category: "Accesorios",
    slug: "anker-usb-c-hub-7-in-1-macbook",
    description: "Hub USB-C con HDMI, USB-A y lector de tarjetas.",
  },

  // ========= EXTRA ELECTRÓNICA / TECH =========
  {
    id: "73",
    title: "Samsung T7 Portable SSD 1TB",
    store: "Amazon",
    priceUSD: 119,
    estimatedUSD: 190,
    category: "Electrónica",
    slug: "samsung-t7-portable-ssd-1tb",
    description: "SSD portátil ultrarrápido USB-C de 1TB.",
  },
  {
    id: "74",
    title: "WD Black SN850X NVMe SSD 2TB",
    store: "Amazon",
    priceUSD: 249,
    estimatedUSD: 360,
    category: "Electrónica",
    slug: "wd-black-sn850x-nvme-ssd-2tb",
    description: "SSD NVMe de alto rendimiento para gaming y creadores.",
  },
  {
    id: "75",
    title: "Elgato Stream Deck MK.2",
    store: "Amazon",
    priceUSD: 149,
    estimatedUSD: 220,
    category: "Electrónica",
    slug: "elgato-stream-deck-mk2",
    description: "Controlador con teclas LCD para streaming y automatizaciones.",
  },
  {
    id: "76",
    title: "Blue Yeti USB Microphone Blackout",
    store: "Amazon",
    priceUSD: 129,
    estimatedUSD: 190,
    category: "Electrónica",
    slug: "blue-yeti-usb-microphone-blackout",
    description: "Micrófono USB Blue Yeti, ideal para podcasts y streaming.",
  },
  {
    id: "77",
    title: "Logitech C920S HD Pro Webcam",
    store: "Amazon",
    priceUSD: 69,
    estimatedUSD: 125,
    category: "Electrónica",
    slug: "logitech-c920s-hd-pro-webcam",
    description: "Webcam Full HD 1080p con tapa de privacidad.",
  },
  {
    id: "78",
    title: "Roku Streaming Stick 4K",
    store: "Amazon",
    priceUSD: 49,
    estimatedUSD: 105,
    category: "Electrónica",
    slug: "roku-streaming-stick-4k",
    description: "Stick de streaming 4K compatible con los principales servicios.",
  },

  // ========= EXTRA HOGAR / VIDA DIARIA =========
  {
    id: "79",
    title: "S'well Stainless Steel Water Bottle 17oz",
    store: "Amazon",
    priceUSD: 35,
    estimatedUSD: 85,
    category: "Hogar",
    slug: "swell-stainless-steel-water-bottle-17oz",
    description: "Botella térmica de acero inoxidable que mantiene temperatura.",
  },
  {
    id: "80",
    title: "YETI Rambler 20 oz Tumbler",
    store: "YETI",
    priceUSD: 35,
    estimatedUSD: 90,
    category: "Hogar",
    slug: "yeti-rambler-20-oz-tumbler",
    description: "Vaso térmico YETI Rambler de 20oz para bebidas frías o calientes.",
  },
  {
    id: "81",
    title: "Hydro Flask 32oz Wide Mouth Bottle",
    store: "Hydro Flask",
    priceUSD: 49,
    estimatedUSD: 110,
    category: "Hogar",
    slug: "hydro-flask-32oz-wide-mouth-bottle",
    description: "Botella térmica Hydro Flask de 32oz.",
  },
  {
    id: "82",
    title: "OXO Good Grips 10-Piece POP Container Set",
    store: "Amazon",
    priceUSD: 112,
    estimatedUSD: 190,
    category: "Hogar",
    slug: "oxo-good-grips-10-piece-pop-container-set",
    description: "Set de contenedores herméticos para la cocina.",
  },
  {
    id: "83",
    title: "Simplehuman 45L Stainless Steel Trash Can",
    store: "Amazon",
    priceUSD: 139,
    estimatedUSD: 220,
    category: "Hogar",
    slug: "simplehuman-45l-stainless-steel-trash-can",
    description: "Tacho de basura de acero inoxidable con pedal.",
  },
  {
    id: "84",
    title: "Beats Studio Pro Wireless Headphones",
    store: "Apple",
    priceUSD: 349,
    estimatedUSD: 470,
    category: "Electrónica",
    slug: "beats-studio-pro-wireless-headphones",
    description: "Auriculares Beats Studio Pro con cancelación de ruido.",
  },

  // ========= EXTRA MODA / ACCESORIOS =========
  {
    id: "85",
    title: "Nike Club Cap Unstructured Black",
    store: "Nike",
    priceUSD: 28,
    estimatedUSD: 75,
    category: "Accesorios",
    slug: "nike-club-cap-unstructured-black",
    description: "Gorra Nike clásica de algodón sin estructura.",
  },
  {
    id: "86",
    title: "Carhartt Acrylic Watch Hat Beanie",
    store: "Amazon",
    priceUSD: 24,
    estimatedUSD: 70,
    category: "Accesorios",
    slug: "carhartt-acrylic-watch-hat-beanie",
    description: "Gorro Carhartt grueso, ideal para invierno.",
  },
  {
    id: "87",
    title: "Herschel Chapter Travel Kit",
    store: "Amazon",
    priceUSD: 39,
    estimatedUSD: 95,
    category: "Accesorios",
    slug: "herschel-chapter-travel-kit",
    description: "Neceser Herschel para viajes.",
  },
  {
    id: "88",
    title: "Apple Leather Wallet with MagSafe",
    store: "Apple",
    priceUSD: 59,
    estimatedUSD: 120,
    category: "Accesorios",
    slug: "apple-leather-wallet-magsafe",
    description: "Billetera de cuero Apple con MagSafe para iPhone.",
  },
  {
    id: "89",
    title: "Bellroy Travel Wallet RFID",
    store: "Amazon",
    priceUSD: 139,
    estimatedUSD: 210,
    category: "Accesorios",
    slug: "bellroy-travel-wallet-rfid",
    description: "Billetera de viaje Bellroy con protección RFID.",
  },
  {
    id: "90",
    title: "Samsonite Winfield 3 DLX Hardside Luggage 28\"",
    store: "Amazon",
    priceUSD: 259,
    estimatedUSD: 380,
    category: "Accesorios",
    slug: "samsonite-winfield-3-dlx-hardside-28",
    description: "Valija rígida grande Samsonite para viajes internacionales.",
  },

  // ========= EXTRA TECH / CREATIVE =========
  {
    id: "91",
    title: "Apple MacBook Air 13\" M2 8GB 256GB",
    store: "Apple",
    priceUSD: 1099,
    estimatedUSD: 1450,
    category: "Electrónica",
    slug: "apple-macbook-air-13-m2-8gb-256gb",
    description: "MacBook Air con chip M2, ultraliviana y potente.",
  },
  {
    id: "92",
    title: "Dell XPS 13 Plus Laptop 16GB 512GB",
    store: "Dell",
    priceUSD: 1499,
    estimatedUSD: 1950,
    category: "Electrónica",
    slug: "dell-xps-13-plus-16gb-512gb",
    description: "Notebook Dell XPS 13 Plus premium para trabajo profesional.",
  },
  {
    id: "93",
    title: "iPad Pro 11\" M4 256GB Wi-Fi",
    store: "Apple",
    priceUSD: 999,
    estimatedUSD: 1350,
    category: "Electrónica",
    slug: "ipad-pro-11-m4-256gb-wifi",
    description: "iPad Pro 11\" con chip M4 para creadores exigentes.",
  },
  {
    id: "94",
    title: "Apple Pencil Pro",
    store: "Apple",
    priceUSD: 129,
    estimatedUSD: 190,
    category: "Electrónica",
    slug: "apple-pencil-pro",
    description: "Lápiz Apple Pencil Pro compatible con iPad Pro y iPad Air nuevos.",
  },
  {
    id: "95",
    title: "Wacom Intuos Pro Medium Pen Tablet",
    store: "Amazon",
    priceUSD: 379,
    estimatedUSD: 520,
    category: "Electrónica",
    slug: "wacom-intuos-pro-medium-pen-tablet",
    description: "Tableta gráfica Wacom para ilustradores y diseñadores.",
  },
  {
    id: "96",
    title: "Canon EOS R50 Mirrorless Camera Kit 18-45mm",
    store: "Amazon",
    priceUSD: 799,
    estimatedUSD: 1100,
    category: "Electrónica",
    slug: "canon-eos-r50-mirrorless-camera-18-45mm",
    description: "Cámara mirrorless Canon EOS R50 con lente 18-45mm.",
  },

  // ========= EXTRA VIAJE / OUTDOOR =========
  {
    id: "97",
    title: "Osprey Farpoint 40 Travel Backpack",
    store: "Amazon",
    priceUSD: 219,
    estimatedUSD: 320,
    category: "Accesorios",
    slug: "osprey-farpoint-40-travel-backpack",
    description: "Mochila de viaje Osprey Farpoint 40 apta cabina.",
  },
  {
    id: "98",
    title: "Columbia Watertight II Men's Jacket",
    store: "Amazon",
    priceUSD: 89,
    estimatedUSD: 150,
    category: "Ropa y moda",
    slug: "columbia-watertight-ii-mens-jacket",
    description: "Campera impermeable Columbia liviana y compacta.",
  },
  {
    id: "99",
    title: "Crocs Classic Clog Unisex Black",
    store: "Amazon",
    priceUSD: 49,
    estimatedUSD: 100,
    category: "Zapatillas",
    slug: "crocs-classic-clog-unisex-black",
    description: "Crocs clásicas unisex color negro.",
  },
  {
    id: "100",
    title: "Therm-a-Rest NeoAir Xlite NXT Sleeping Pad Regular",
    store: "Amazon",
    priceUSD: 219,
    estimatedUSD: 320,
    category: "Hogar",
    slug: "therm-a-rest-neoair-xlite-nxt-regular",
    description: "Colchoneta inflable ultraliviana para camping y trekking.",
  },
];
